#version: '3.6'
services:

  # PostgreSQL
  postgres_image:
    # container_name: postgres
    # image: postgres
    restart: always
    build: ./API/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # POSTGRES_URL: postgres://admin:password@localhost:5432/blogdb
      POSTGRES_DB: blogdb
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"

  # # Redis
  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - "6379:6379"

  # Backend
  blog-sys-api:
    # env_file:
    #   - ./.private/api-keys.env "Another way to insert env variables"
    # container_name: backend
    # image: mcr.microsoft.com/dotnet/aspnet:5.0
    depends_on:
      - "postgres_image"
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/source
    command: dotnet watch run
    working_dir: /source/API/
    ports:
      - "5001:5001"
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # ASPNETCORE_ENVIRONMENT: "PRODUCTION"
      MY_PG_CS: "User ID=admin;Username=admin;Password=admin;Host=localhost;Port=5432;Database=blogdb;"
      ANDREI_CONNECTION_STRING: "postgres://admin:admin@postgres_image:5432/blogdb"
      #DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=blogdb;username=admin;password=password"
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=blogdb;username=admin;password=admin"
      PG_CONNECTION_STRING: "Server=localhost;Port=5432;User Id=admin;Password=admin;Database=blogdb;SSL Mode=Require;TrustServerCertificate=True"
      POSTGRES_HOST: postgres_image
    #   REDIS_URI: redis://redis:6379
